add a command help, with a template
angolaosc/savanna-bot pull request #18
Opened 2023-08-20 17:34 UTC by matiasdev30

2023-08-20 17:35 UTC, matiasdev30 commented
@antonio-pedro99 de uma olhada

2023-08-20 17:42 UTC, antonio-pedro99 requested changes
@matiasdev30 Obrigado pela PR.
Bom começo para ser sincero, estamos perto. 
Deixei alguns comentários.

2023-08-20 17:42 UTC, antonio-pedro99 commented on src/bot.py
> +@bot.command(name='help', description="Retrieve information about the available commands and their usage")
Bom começo. 
O que você acha, invés de comando criar um argumento?
Atualmente o comando para usar o bot é `svn`, eu acho que seria algo tipo, `/svn help`, e não simplesmente `help` o que é muito global.

2023-08-20 17:42 UTC, antonio-pedro99 commented on src/bot.py
> +    logging.info("""
Bem, nós não estamos a lidar com um program CLI. Mas sim um bot, você não precisa fazer log, mas sim enviar mensagem para discord.

2023-08-20 17:42 UTC, antonio-pedro99 commented on src/bot.py
> +    logging.info("""
Por outra, a função deve ser assíncrona.

2023-08-20 17:44 UTC, matiasdev30 commented on src/bot.py
> +    logging.info("""
Agora percebi mesmo na verdade, obrigado

2023-08-20 17:44 UTC, matiasdev30 commented on src/bot.py
> +    logging.info("""
farei as devidas alterações

2023-08-20 17:45 UTC, antonio-pedro99 commented
@matiasdev30 de uma olhada nesta linha

https://github.com/angolaosc/savanna-bot/blob/22b5ce8b7e44fffb319cd5743b62b2e192d83c2e/src/bot.py#L42

Nós precisamos primeiro reconhecer o argumento `help`. Você pode, por exemplo, procurar pela palavra `help` na variável `args`, eu acho que precisamos ter certeza que só temos um argumento e este argumento é `help`. Se sim, eu chamaria a função para enviar a mensagem de ajuda.

2023-08-20 17:55 UTC, antonio-pedro99 commented on src/bot.py
> +    logging.info("""
Boas mano! Esperando

2023-08-20 17:59 UTC, matiasdev30 commented
Percebi logo, mais nesse caso a mensagem de ajuda retornada será estáticas ou aquele ref do github mais com os dados crucias filtrados

2023-08-20 18:00 UTC, matiasdev30 commented on src/bot.py
> +@bot.command(name='help', description="Retrieve information about the available commands and their usage")
Tomei nota, thanks

2023-08-20 18:02 UTC, matiasdev30 commented on src/bot.py
> +    logging.info("""
Na verdade viajei mesmo em fechar a issue que estava implementado para retornar a informação de ajuda na linha de comando 😂 

podes ver essa questão https://github.com/angolaosc/savanna-bot/pull/18#issuecomment-1685354214

2023-08-20 18:04 UTC, matiasdev30 commented
> Percebi logo, mais nesse caso a mensagem de ajuda retornada será estáticas ou aquele ref do github mais com os dados crucias filtrados @antonio-pedro99

2023-08-20 18:07 UTC, antonio-pedro99 commented
> Percebi logo, mais nesse caso a mensagem de ajuda retornada será estáticas ou aquele ref do github mais com os dados crucias filtrados @antonio-pedro99

Podemos começar com algo estático. 
Eu acho que podemos nos focar nos comandos simples. Vê os comandos válidos aqui: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests
A ideia é o usuário saber os comandos essenciais, pesquisar por:
[- lingugagem de programação ](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-language)
[-por data de update e criação](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-when-an-issue-or-pull-request-was-created-or-last-updated)
e podes explorar outrras alternativas aqui
https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

2023-08-20 18:24 UTC, matiasdev30 commented
@antonio-pedro99 podes validar esse commit af248ca7e8544b3fb850644ba73335ac45a79dae

2023-08-20 18:30 UTC, antonio-pedro99 commented on src/bot.py
> +@bot.command(name='/svn help', description="Retrieve information about the available commands and their usage")
Você não precisa esse decorador por aqui.
Não se preocupa em definir o comando. Tente lidar com os argumentos na função `search_send`

2023-08-20 18:34 UTC, matiasdev30 commented on src/bot.py
> +@bot.command(name='/svn help', description="Retrieve information about the available commands and their usage")
Na verdade é esss que estava

2023-08-20 18:37 UTC, antonio-pedro99 commented on src/bot.py
> +    if '/svn help' in args:
`/svn` não faz part do argumento.
seria 
```python
if 'help' in args:
   # do something
```
Mas conforme disse anteriormente, não será suficiente saber que `help` está nos argumentos, precisamos ter certeza que é o único argumento.

Aqui estão algumas razões.

Na actual versão, 
- se você  enviar `/svn help`, você vai receber issues rotulados com `good first issue` e que no corpo ou no title da issue tem a palavra `help`
- se você enviar `/svn help language:python`, você vai receber issues de repositórios onde a linguagem de programação predominante é python, rotulados com `good first issue` e que no corpo ou no title da issue tem a palavra `help`.

Então só checkar que `help` está nos argumentos não funciona.

2023-08-20 18:38 UTC, antonio-pedro99 commented on .vscode/settings.json
> +{
Eu não acho que precisamos deste ficheiro. Porfavor remova e adicione o `.vscode` no `.gitignore`

2023-08-20 18:40 UTC, antonio-pedro99 commented on src/bot.py
> +            language:LANGUAGE   Example: language:ruby state:open matches open issues that are in Ruby repositories.
Eu acho que o exemplo tem que incluir o comando do bot, tipo `/svn language:ruby state:open` matches open issues that are in Ruby repositories.

2023-08-20 18:40 UTC, antonio-pedro99 commented on src/bot.py
> +            Description: An example program to demonstrate how to organize help in the command-line interface.
Não precisamos da palavra command-line e organize aqui.

2023-08-20 18:41 UTC, antonio-pedro99 commented on src/bot.py
> +            created:YYYY-MM-DD	Example: language:c# created:<2011-01-01 state:open matches open issues that were created before 2011 in repositories written in C#.
vê o meu comment anterior.

2023-08-20 18:42 UTC, antonio-pedro99 commented on src/bot.py
> +    else:
Eu não acho que precisamos deste else aqui.

2023-08-20 18:42 UTC, antonio-pedro99 commented on src/bot.py
> +        await ctx.send(("""
Também não precisamos enviar esta mensagem.

2023-08-20 18:42 UTC, antonio-pedro99 commented on src/bot.py
> +The most similar command is
Também não precisamos esta mensagem.

2023-08-20 20:36 UTC, matiasdev30 commented
@antonio-pedro99 subi as mudanças prevista, mais eu não entendi todo o feedback que deste

2023-08-21 09:36 UTC, antonio-pedro99 requested changes
Atualmente temos este bloco é a implementação da função `search_send(ctx, *args)`

```python
# automatically parse all the arguments
    params = ' '.join(args)
    results = await searcher.search(params)
    if results:
        for result in results:
            await ctx.send(result.html_url)
    else:
        await ctx.send("No issues found")
```
`args` é a lista de argumentos que o usuário enviará.
Na atual implementação(no código acima) passamos diretamente todos os argumentos como parâmetros para realizar a nossa pesquisa no GitHub e enviamos o resultado no usuário.

Porém, para adicionar o argumento de ajuda `help`, nós precisamos manipular a variável `args` e certificar-se que essa lista só contém a palavra `help` ou ainda melhor `--help`.

Acho que eu antes de passar os parâmetros para a pesquisa no GitHub, eu ia verificar se só existe o argumento `--help` na lista de argumentos `args`, se existe, eu chamaria a função que você criou e retornaria um null para quebrar a execução.

2023-08-21 09:36 UTC, antonio-pedro99 commented on .vscode/settings.json
> +{
Este ficheiro precisa ser removido deste commit.

2023-08-21 09:36 UTC, antonio-pedro99 commented on .gitignore
> +/vscode/settings.json
Não acho que precisamos essa linha.

`.vscode/` deve incluir todos os ficheiros dentro desse directory.

2023-08-21 09:36 UTC, antonio-pedro99 commented on src/bot.py
> +    if '/svn help' in args:
Está condição não pertence aqui.
Vou deixar um comentário explicando.

2023-08-21 09:36 UTC, antonio-pedro99 commented on src/bot.py
> +            /svn language:LANGUAGE   Example: language:ruby state:open matches open issues that are in Ruby repositories.
```suggestion
        language:LANGUAGE   Example: /svn language:ruby state:open matches open issues that are in Ruby repositories.
```

2023-08-21 09:36 UTC, antonio-pedro99 commented on src/bot.py
> +            /svn created:YYYY-MM-DD	Example: language:c# created:<2011-01-01 state:open matches open issues that were created before 2011 in repositories written in C#.
```suggestion
        created:YYYY-MM-DD	Example: /svn language:c# created:<2011-01-01 state:open matches open issues that were created before 2011 in repositories written in C#.
```

2023-08-21 09:36 UTC, antonio-pedro99 commented on src/bot.py
> +            /svn updated:YYYY-MM-DD Example: weird in:body updated:>=2013-02-01 matches issues with the word "weird" in the body that were updated after February 2013.
```suggestion
        updated:YYYY-MM-DD Example: /svn weird in:body updated:>=2013-02-01 matches issues with the word "weird" in the body that were updated after February 2013.   
```

2023-08-21 23:57 UTC, matiasdev30 commented
> Atualmente temos este bloco é a implementação da função `search_send(ctx, *args)`
> 
> 
> 
> ```python
> 
> # automatically parse all the arguments
> 
>     params = ' '.join(args)
> 
>     results = await searcher.search(params)
> 
>     if results:
> 
>         for result in results:
> 
>             await ctx.send(result.html_url)
> 
>     else:
> 
>         await ctx.send("No issues found")
> 
> ```
> 
> `args` é a lista de argumentos que o usuário enviará.
> 
> Na atual implementação(no código acima) passamos diretamente todos os argumentos como parâmetros para realizar a nossa pesquisa no GitHub e enviamos o resultado no usuário.
> 
> 
> 
> Porém, para adicionar o argumento de ajuda `help`, nós precisamos manipular a variável `args` e certificar-se que essa lista só contém a palavra `help` ou ainda melhor `--help`.
> 
> 
> 
> Acho que eu antes de passar os parâmetros para a pesquisa no GitHub, eu ia verificar se só existe o argumento `--help` na lista de argumentos `args`, se existe, eu chamaria a função que você criou e retornaria um null para quebrar a execução. 

Então a condição seria if *args == "--help" porque é para verificar se só contém o comando --help, caso tenha, chamo a mensagem de ajuda, e retorno null para sair da função

2023-08-22 00:00 UTC, matiasdev30 commented
Verifica só as alterações feitas no último commit

2023-08-22 09:00 UTC, antonio-pedro99 commented on src/bot.py
> +            /svn language:LANGUAGE   Example: language:ruby state:open matches open issues that are in Ruby repositories.
@matiasdev30 podes aceitar essas sugestões?

2023-08-22 09:00 UTC, antonio-pedro99 commented on src/bot.py
> +            /svn created:YYYY-MM-DD	Example: language:c# created:<2011-01-01 state:open matches open issues that were created before 2011 in repositories written in C#.
Essa tbm

2023-08-22 09:00 UTC, antonio-pedro99 commented on src/bot.py
> +            /svn updated:YYYY-MM-DD Example: weird in:body updated:>=2013-02-01 matches issues with the word "weird" in the body that were updated after February 2013.
Essa tbm

2023-08-22 09:02 UTC, antonio-pedro99 commented
> > Atualmente temos este bloco é a implementação da função `search_send(ctx, *args)`
> > ```python
> > # automatically parse all the arguments
> > 
> >     params = ' '.join(args)
> > 
> >     results = await searcher.search(params)
> > 
> >     if results:
> > 
> >         for result in results:
> > 
> >             await ctx.send(result.html_url)
> > 
> >     else:
> > 
> >         await ctx.send("No issues found")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `args` é a lista de argumentos que o usuário enviará.
> > Na atual implementação(no código acima) passamos diretamente todos os argumentos como parâmetros para realizar a nossa pesquisa no GitHub e enviamos o resultado no usuário.
> > Porém, para adicionar o argumento de ajuda `help`, nós precisamos manipular a variável `args` e certificar-se que essa lista só contém a palavra `help` ou ainda melhor `--help`.
> > Acho que eu antes de passar os parâmetros para a pesquisa no GitHub, eu ia verificar se só existe o argumento `--help` na lista de argumentos `args`, se existe, eu chamaria a função que você criou e retornaria um null para quebrar a execução.
> 
> Então a condição seria if *args == "--help" porque é para verificar se só contém o comando --help, caso tenha, chamo a mensagem de ajuda, e retorno null para sair da função

Não está correto, `*args` é uma lista. Você deve verificar se essa lista contém `--help` e o tamanho da mesma lista é 1.

2023-08-22 09:05 UTC, antonio-pedro99 commented on src/bot.py
> +    if '--help' == args:
Boa, está quase lá!
Só precisas mudar essa condição. 
Por outra, eu acho conveniente testar antes de fazer commit. 
Se você precisa ajuda para testar, vamos conversar no discord.

2023-08-22 09:06 UTC, antonio-pedro99 commented on src/bot.py
> +    if '--help' == args:
Expliquei noutro comentário o que você precisa fazer.

2023-08-25 08:34 UTC, antonio-pedro99 commented on .vscode/settings.json
> +{
@matiasdev30 vais remover este ficheiro?

2023-10-04 21:12 UTC, antonio-pedro99 commented
Olá @matiasdev30 nas calmas mano??
ainda trabalhas nessa cena?

2023-10-26 14:43 UTC, antonio-pedro99 commented
Fechado por inatividade.

2023-10-26 14:43 UTC, closed without merging